CREATE DATABASE paintballDB;

CREATE TABLE paintballDB.CANCHAS(
IdCancha INT NOT NULL AUTO_INCREMENT,
descripcionCancha VARCHAR(50) NOT NULL,
CONSTRAINT PK_Cancha PRIMARY KEY(IdCancha)
);

CREATE TABLE paintballDB.CATEGORIAS(
IdCategoria INT NOT NULL AUTO_INCREMENT,
descripcionCategoria VARCHAR(50) NOT NULL,
CONSTRAINT PK_Categoria PRIMARY KEY(IdCategoria)
);

CREATE TABLE paintballDB.DIAS(
IdDia INT NOT NULL AUTO_INCREMENT,
descripcionDia VARCHAR(25) NOT NULL,
CONSTRAINT PK_Dia PRIMARY KEY(IdDia)
);

CREATE TABLE paintballDB.ESTADOS(
IdEstado INT NOT NULL AUTO_INCREMENT,
DescripcionEstado VARCHAR(50),
CONSTRAINT PK_Estado PRIMARY KEY(IdEstado)
);

CREATE TABLE paintballDB.FACTURAS(
IdFactura INT NOT NULL AUTO_INCREMENT,
NumeroFactura VARCHAR(50) NOT NULL,
FechaEmision DATE NOT NULL,
HoraEmision DATETIME NOT NULL,
CONSTRAINT PK_Factura PRIMARY KEY(IdFactura)
);

CREATE TABLE paintballDB.PROVINCIAS(
IdProvincia INT NOT NULL AUTO_INCREMENT,
DescripcionProvincia VARCHAR(50) NOT NULL,
CONSTRAINT PK_Provincia PRIMARY KEY(IdProvincia)
);

CREATE TABLE paintballDB.SEXOS(
IdSexo INT NOT NULL AUTO_INCREMENT,
DescripcionSexo VARCHAR(25) NOT NULL,
CONSTRAINT PK_Sexo PRIMARY KEY(IdSexo)
);

CREATE TABLE paintballDB.TIPOUSUARIOS(
IdTipoUsuario INT NOT NULL AUTO_INCREMENT,
DescripcionTipo VARCHAR(50),
CONSTRAINT PK_TipoUsuario PRIMARY KEY(IdTipoUsuario)
);

CREATE TABLE paintballDB.CANTONES(
IdCanton INT NOT NULL AUTO_INCREMENT,
Provincia INT NOT NULL,
DescripcionCanton VARCHAR(50) NOT NULL,
CONSTRAINT PK_Canton PRIMARY KEY(IdCanton),
CONSTRAINT FK_ProvinciaCanton FOREIGN KEY(Provincia)
REFERENCES PROVINCIAS(IdProvincia)
);

CREATE TABLE paintballDB.DISTRITOS(
IdDistrito INT NOT NULL AUTO_INCREMENT,
Canton INT NOT NULL,
DescripcionDistrito VARCHAR(50) NOT NULL,
CONSTRAINT PK_Distrito PRIMARY KEY(IdDistrito),
CONSTRAINT FK_CantonDistrito FOREIGN KEY(Canton)
REFERENCES CANTONES(IdCanton)
);

CREATE TABLE paintballDB.DIRECCIONES(
IdDireccion INT NOT NULL AUTO_INCREMENT,
Distrito INT NOT NULL,
DescripcionDireccion VARCHAR(50) NOT NULL,
CONSTRAINT PK_Direccion PRIMARY KEY(IdDireccion),
CONSTRAINT FK_DistritoDireccion FOREIGN KEY(Distrito)
REFERENCES DISTRITOS(IdDistrito)
);

CREATE TABLE paintballDB.PROVEEDORES(
IdProveedor INT NOT NULL AUTO_INCREMENT,
DireccionProveedor INT NOT NULL,
NombreProveedor VARCHAR(50) NOT NULL,
TelefonoProveedor VARCHAR(50) NOT NULL,
CorreoProveedor VARCHAR(100) NOT NULL,
CONSTRAINT PK_Proveedor PRIMARY KEY(IdProveedor),
CONSTRAINT FK_DireccionProveedor FOREIGN KEY(DireccionProveedor)
REFERENCES DIRECCIONES(IdDireccion)
);

CREATE TABLE paintballDB.EQUIPOS(
IdEquipo INT NOT NULL AUTO_INCREMENT,
Categoria INT NOT NULL,
Proveedor INT NOT NULL,
DescripcionEquipo VARCHAR(50) NOT NULL,
CantidadActual INT NOT NULL,
CONSTRAINT PK_Equipo PRIMARY KEY(IdEquipo),
CONSTRAINT FK_CategoriaEquipo FOREIGN KEY(Categoria)
REFERENCES CATEGORIAS(IdCategoria),
CONSTRAINT FK_ProveedorEquipo FOREIGN KEY(Proveedor)
REFERENCES PROVEEDORES(IdProveedor)
);

CREATE TABLE paintballDB.USUARIOS(
IdUsuario INT NOT NULL AUTO_INCREMENT,
DireccionUsuario INT NOT NULL,
Sexo INT NOT NULL,
TipoUsuario INT NOT NULL,
NombreUsuario VARCHAR(50) NOT NULL,
PrimerApellido VARCHAR(50) NOT NULL,
SegundoApellido VARCHAR(50) NOT NULL,
TelefonoUsuario VARCHAR(50) NOT NULL,
CorreoUsuario VARCHAR(100) NOT NULL,
FechaNacimiento DATE NOT NULL,
ClaveUsuario VARCHAR(50) NOT NULL,
CONSTRAINT PK_Usuario PRIMARY KEY(IdUsuario),
CONSTRAINT FK_DireccionUsuario FOREIGN KEY(DireccionUsuario)
REFERENCES DIRECCIONES(IdDireccion),
CONSTRAINT FK_SexoUsuario FOREIGN KEY(Sexo)
REFERENCES SEXOS(IdSexo),
CONSTRAINT FK_TipoUsuario FOREIGN KEY(TipoUsuario)
REFERENCES TIPOUSUARIOS(IdTipoUsuario)
);

CREATE TABLE paintballDB.RESERVACIONES(
IdReservacion INT NOT NULL AUTO_INCREMENT,
Usuario INT NOT NULL,
Cancha INT NOT NULL,
DiaReservacion INT NOT NULL,
CodigoQR TEXT(7089) NOT NULL,
FechaReservacion DATE NOT NULL,
HoraReservacion DATETIME NOT NULL,
TamanoGrupo INT NOT NULL,
CONSTRAINT PK_Reservacion PRIMARY KEY(IdReservacion),
CONSTRAINT FK_UsuarioReservacion FOREIGN KEY(Usuario)
REFERENCES USUARIOS(IdUsuario),
CONSTRAINT FK_CanchaReservacion FOREIGN KEY(Cancha)
REFERENCES CANCHAS(IdCancha),
CONSTRAINT FK_DiaReservacion FOREIGN KEY(DiaReservacion)
REFERENCES DIAS(IdDia)
);

CREATE TABLE paintballDB.PAQUETES(
IdPaquete INT NOT NULL AUTO_INCREMENT,
Estado INT NOT NULL,
DescripcionPaquete VARCHAR(50) NOT NULL,
Precio FLOAT NOT NULL,
MinimoPersonas INT NOT NULL,
CONSTRAINT PK_Paquete PRIMARY KEY(IdPaquete),
CONSTRAINT FK_EstadoPaquete FOREIGN KEY(Estado)
REFERENCES ESTADOS(IdEstado)
);

CREATE TABLE paintballDB.FACTURASPAQUETES(
IdFacturasPaquetes INT NOT NULL AUTO_INCREMENT,
Factura INT NOT NULL,
PaqueteFactura INT NOT NULL,
CONSTRAINT PK_FP PRIMARY KEY(IdFacturasPaquetes),
CONSTRAINT FK_FacturaFP FOREIGN KEY(Factura)
REFERENCES FACTURAS(IdFactura),
CONSTRAINT FK_PaqueteFP FOREIGN KEY(PaqueteFactura)
REFERENCES PAQUETES(IdPaquete)
);

CREATE TABLE paintballDB.PAQUETESRESERVACIONES(
IdPaquetesReservaciones INT NOT NULL AUTO_INCREMENT,
Reservacion INT NOT NULL,
PaqueteReservacion INT NOT NULL,
Cedula VARCHAR(25) NOT NULL,
CONSTRAINT PK_PR PRIMARY KEY(IdPaquetesReservaciones),
CONSTRAINT PK_ReservacionPR FOREIGN KEY(Reservacion)
REFERENCES Reservaciones(IdReservacion),
CONSTRAINT PK_PaquetePR FOREIGN KEY(PaqueteReservacion)
REFERENCES PAQUETES(IdPaquete)
);

CREATE TABLE paintballDB.EQUIPOSPAQUETES(
IdEquipoPaquete INT NOT NULL AUTO_INCREMENT,
Equipo INT NOT NULL,
PaqueteEquipo INT NOT NULL,
CONSTRAINT PK_EP PRIMARY KEY(IdEquipoPaquete),
CONSTRAINT FK_EquipoEP FOREIGN KEY(Equipo)
REFERENCES EQUIPOS(IdEquipo),
CONSTRAINT FK_PaqueteEP FOREIGN KEY(PaqueteEquipo)
REFERENCES PAQUETES(IdPaquete)
);

/*DROP DATABASE paintballDB;*/
